### ISSUE TITLE
cursor don't preserve font style (eg. italic)

### ISSUE THREAD

**Issue by gattomarcomix** [rohit-px2/nvui#106] opened 2021-12-03 16:33 UTC
![cursor_on_italic](https://user-images.githubusercontent.com/94183109/144638129-245aee8e-a26f-4487-bff8-6353048e13bd.png)

the picture shows nvui and nvim-qt side by side. 
nvui is on  left side: look at the character P inside the cursor rectangle.
This is my configuration:

`" Cursor style: vertical in insert mode, block in normal
:set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor,sm:block-blinkwait175-blinkoff150-blinkon175

:hi Cursor       guifg=white     guibg=#00c6fa 
`

thanks for 0.2.1 release 🥇  more and more solid!

**Comment by rohit-px2** [comment] 2021-12-04 16:39
That's the intended behaviour, `Cursor` is a highlight group and since you haven't set any font options it defaults to `gui=NONE` which has no italic/bold. If you want it to use italic/bold you can do `hi Cursor gui=bold,italic`.

**Comment by gattomarcomix** [comment] 2021-12-04 20:25
https://user-images.githubusercontent.com/94183109/144723413-61c445eb-0ded-4cdd-823a-b5f1b7e63701.mp4

Sure, I know what you mean. In my opinion your concept is correct but the behavior of nvim-qt gives a better feeling.
Of course we talk about preferences.
At this point I have no other reports. nvui is a rock!

**Comment by rohit-px2** [comment] 2021-12-16 16:03
I added this to the [cursor effects branch](https://github.com/rohit-px2/nvui/tree/cursor_effects), will close this issue when I merge it in.

**Comment by gattomarcomix** [comment] 2021-12-17 07:30
yay!
nvui's popularity will soon surpass that of everyone else...
I'm testing the 'cursor_effects' branch. 
When the next version is released I'm ready for a second round of reports.
The style of the text under the cursor is exactly as expected. :-)
Thank you!

**Closed** 2021-12-23 17:01 UTC
