### ISSUE TITLE
Core dump: Assertion `editor_area' failed

### ISSUE THREAD

**Issue by the-glu** [rohit-px2/nvui#31] opened 2021-08-30 13:49 UTC
Hello,

I tried to build the package on Archlinux.

Build is fine (with the fix 56c4577 ), but at start up there is a crash:

./nvui
nvui: nvui/src/cursor.cpp:37: Cursor::Cursor(EditorArea*): Assertion `editor_area' failed.
zsh: abort (core dumped)  ./nvui

I can provide versions of libraries if needed :)

Thanks a lot and have a nice day!

**Comment by tom-kuca** [comment] 2021-08-30 13:59
I can confirm it, I'm also ArchLinux. I'm using wayland (swayvm).

https://github.com/rohit-px2/nvui/blob/56c45771eab60258bbf105b16e175da4cad770ee/src/cursor.cpp#L37

nvui starts if I remove the assertation and works without any obvious problem. My guess is that the `assert` was intended for the method argument `ea`, not for `editor_area`.

**Comment by rohit-px2** [comment] 2021-08-30 14:00
Yeah, I just saw it. I was intending to assert `ea`.

**Comment by rohit-px2** [comment] 2021-08-30 14:02
@tom-kuca @the-glu I've fixed the assertion on the latest commit.

**Comment by the-glu** [comment] 2021-08-30 14:06
I can confirm it's working now, thanks for the quick fix :)

**Comment by rohit-px2** [comment] 2021-08-30 14:15
Good to hear! I'll close this issue then.

**Closed by rohit-px2** 2021-08-30 14:15 UTC
